In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px

In [3]:
df = pd.read_excel('../data/raw/Telco_customer_churn.xlsx')

In [13]:
df.head(1)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer

In [5]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='str')

In [6]:
df.shape

(7043, 33)

In [11]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.info

<bound method DataFrame.info of       CustomerID  Count        Country       State          City  Zip Code  \
0     3668-QPYBK      1  United States  California   Los Angeles     90003
1     9237-HQITU      1  United States  California   Los Angeles     90005
2     9305-CDSKC      1  United States  California   Los Angeles     90006
3     7892-POOKP      1  United States  California   Los Angeles     90010
4     0280-XJGEX      1  United States  California   Los Angeles     90015
...          ...    ...            ...         ...           ...       ...
7038  2569-WGERO      1  United States  California       Landers     92285
7039  6840-RESVB      1  United States  California      Adelanto     92301
7040  2234-XADUH      1  United States  California         Amboy     92304
7041  4801-JZAZL      1  United States  California  Angelus Oaks     92305
7042  3186-AJIEK      1  United States  California  Apple Valley     92308

                    Lat Long   Latitude   Longitude  Gender  ...  \
0     33.964131, -118.272783  33.964131 -118.272783    Male  ...
1      34.059281, -118.30742  34.059281 -118.307420  Female  ...
2     34.048013, -118.293953  34.048013 -118.293953  Female  ...
3     34.062125, -118.315709  34.062125 -118.315709  Female  ...
4     34.039224, -118.266293  34.039224 -118.266293    Male  ...
...                      ...        ...         ...     ...  ...
7038  34.341737, -116.539416  34.341737 -116.539416  Female  ...
7039  34.667815, -117.536183  34.667815 -117.536183    Male  ...
7040  34.559882, -115.637164  34.559882 -115.637164  Female  ...
7041     34.1678, -116.86433  34.167800 -116.864330  Female  ...
7042  34.424926, -117.184503  34.424926 -117.184503    Male  ...

            Contract Paperless Billing             Payment Method  \
0     Month-to-month               Yes               Mailed check
1     Month-to-month               Yes           Electronic check
2     Month-to-month               Yes           Electronic check
3     Month-to-month               Yes           Electronic check
4     Month-to-month               Yes  Bank transfer (automatic)
...              ...               ...                        ...
7038        Two year               Yes  Bank transfer (automatic)
7039        One year               Yes               Mailed check
7040        One year               Yes    Credit card (automatic)
7041  Month-to-month               Yes           Electronic check
7042        Two year               Yes  Bank transfer (automatic)

      Monthly Charges Total Charges Churn Label Churn Value Churn Score  CLTV  \
0               53.85        108.15         Yes           1          86  3239
1               70.70        151.65         Yes           1          67  2701
2               99.65         820.5         Yes           1          86  5372
3              104.80       3046.05         Yes           1          84  5003
4              103.70        5036.3         Yes           1          89  5340
...               ...           ...         ...         ...         ...   ...
7038            21.15        1419.4          No           0          45  5306
7039            84.80        1990.5          No           0          59  2140
7040           103.20        7362.9          No           0          71  5560
7041            29.60        346.45          No           0          59  2793
7042           105.65        6844.5          No           0          38  5097

                       Churn Reason
0      Competitor made better offer
1                             Moved
2                             Moved
3                             Moved
4     Competitor had better devices
...                             ...
7038                            NaN
7039                            NaN
7040                            NaN
7041                            NaN
7042                            NaN

[7043 rows x 33 columns]>

In [12]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [14]:
df["Payment Method"].value_counts()

Payment Method
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [15]:
df["Zip Code"].nunique()

1652

In [16]:
sns.countplot(data=df, x="Streaming TV", hue="Churn")

ValueError: Could not interpret value `Churn` for `hue`. An entry with this name does not appear in `data`.

In [17]:
df["Country"].value_counts()

Country
United States    7043
Name: count, dtype: int64

In [18]:
df["State"].value_counts()

State
California    7043
Name: count, dtype: int64

In [19]:
df["City"].nunique()

1129

In [20]:
print(df["Zip Code"].nunique())

1652

In [21]:
print(df["Churn Score"].describe())

count    7043.000000
mean       58.699418
std        21.525131
min         5.000000
25%        40.000000
50%        61.000000
75%        75.000000
max       100.000000
Name: Churn Score, dtype: float64

In [22]:
print(df["CLTV"].describe())

count    7043.000000
mean     4400.295755
std      1183.057152
min      2003.000000
25%      3469.000000
50%      4527.000000
75%      5380.500000
max      6500.000000
Name: CLTV, dtype: float64